@startuml class-diagram-car-rental-company
title Class diagram of car rental company
skinparam ClassAttributeIconSize 0
'skinparam WrapWidth 200
'Use for straight line but now it error
skinparam Linetype ortho
hide circle
skinparam Monochrome true

Class User <<abstract>> {
    - _id: string
    - _name: string
    - _phone: string
    - _password: string
    + Login(): void
    + Logout(): void
    + ViewProfile(): void
    + UpdateProfile(): void
    + ViewCarList(): void
}

Class Customer {
    - _licenseNo: string
    - _expireDate: string
    + ViewMyRentals(): void
}

Class Staff {
    + AddVehicle(): void
    + RemoveVehicle(vecId: string): void
    + UpdateVehicle(vecId: string): void
    + ViewCustomerList(): void
    + ViewDailyReport(): void
    + ViewMonthLyReport(): void
}

Class Report {
    - _dateCreate: DateTime
}

Class StaffList {
    - _staffList: Staff[]
}

Class CustomerList {
    - _customerList: Customer[]
}

Class Contract {
    - _id: string
    - _customerId: string
    - _vehicle: Vehicle
    - _total: double
    - _startDate: DateTime
    - _endDate: DateTime
    - _status: Status
}

Class ContractList {
    - _contractList: Contract[]
}

Class Vehicle {
    - _id: string
    - _name: string
    - _color: string
    - _brand: string
    - _numberOfSeat: int
    - _condition: double
    - _year: int
    - _price: double
    - _available: bool
}

Class Garage {
    - _vehicleList: Vehicle[]
    - _location: string
    - _capacity: int
    + ShowAvailableVehicle(): void
}


Class IListManagement <<interface>>{
    + AddItem(): void
    + RemoveItem(itemId: string): void
    + UpdateItem(itemId: string): void
    + ShowItemList(): void
}

Class IReportGenerator <<interface>> {
    + GenerateDailyReport(): void
    + GenerateMonthlyReport(): void
    + ExportPdf(): void
    + ExportExcel(): void
    + PrintReport(): void
}

Class ISearchCar <<interface>> {
    + SearchByName(name: string): Vehicle
    + SearchByColor(color: string): Vehicle
    + SearchByBrand(brand: string): Vehicle
}

Class IRentCar <<interface>> {
    + CreateContract(): void
    + ViewVehicleInfo(): void
    + PickupVehicle(): void
    + ReturnVehicle(): void
    + PrintContract(): void
    + CancelContract(): void
}

Class ISaleCalculator <<interface>> {
    + CalculateTotalSale(): double
    + CalculateDailySale(): double
    + CalculateMonthlySale(): double
}

Class Status <<enumerate>> {
    + PENDING
    + READY
    + FINISH
    + CANCEL
}

'BEGIN: CLASS RELATION
User <|-- Customer
User <|-- Staff

StaffList "1" -- "1..*" Staff

CustomerList "1" -- "0..*" Customer

'Customer-CustomerList
Customer "1" -- "1" Contract

'Staff-StaffList
Staff "1..*" -- "0..*" Report
Staff "1..*" -- "1" Garage

'Report-Staff

'Contract-Customer
Contract "1" -- "1" Vehicle
Contract "1..*" -- "1" ContractList

'Vehicle-Contract
Vehicle "0..*" -- "1" Garage

'Garage-Vehicle

'ContractList-Contract

IListManagement <|.. CustomerList
IListManagement <|.. ContractList
IListManagement <|.. StaffList
IListManagement <|.. Garage

IReportGenerator <|.. Report

ISearchCar <|.. Staff
ISearchCar <|.. Customer

IRentCar <|.. Customer
IRentCar <|.. Contract

ISaleCalculator <|.. ContractList

Status -- Contract
'END: CLASS RELATION

@enduml